### ISSUE TITLE
Bug/feat: filter unknown Unicode chars but keep music symbols from whisper transcription

### ISSUE THREAD

**Issue by V3ntus** [V3ntus/quint#1]

**Comment by V3ntus** [comment]
Traceback from `charmap` Unicode exception:
```py
Traceback (most recent call last):
  File "C:\sermonindex_audio\chunk_paragraphs.py", line 136, in <module>
    main()
  File "C:\sermonindex_audio\chunk_paragraphs.py", line 125, in main
    chunk_paragraphs_dir(args.i, args.o)
  File "C:\sermonindex_audio\chunk_paragraphs.py", line 78, in chunk_paragraphs_dir
    _input_contents: str = input_file.read().encode("ascii", errors="ignore").decode().replace("\r\n", " ").replace("\n", " ")
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 19721: character maps to <undefined>
```

**Comment by V3ntus** [comment]
`UnicodeDecodeError` fixes

**Comment by turnkit** [comment]
Instead, keep ALL unicode characters, including Chinese, Music symbols, etc.  Try to get everything to process despite odd characters.  (Ignore right-to-left character encoding issues for now.  Hopefully this won't show up.)

**Comment by V3ntus** [comment]
[b4f24d6](https://github.com/V3ntus/quint/commit/b4f24d673079c5bf02bd86cfe4c5a066e24b45d4)

- adds utf-8 read/write support
- checks if output contained unicode, moves them to `sus/` subfolder
