### ISSUE TITLE
processing should continue if an individual file fails

### ISSUE THREAD

**Issue by turnkit** [V3ntus/quint#7]
Still not able to automate a batch since one file causes the whole process to fail.

Regardless of the error, ideally for each failed file that file should be moved to the 3_failed folder and attempts to process the rest of the files should continue onward.

Here's a sample:
--
[INFO]: [24/1472] Sending file contents of C:\sermonindex_audio\bak_whisp_out\txt_to_do/SID1189.mp3.txt to API server on 192.168.0.62:8000...
[INFO]: Writing to C:\sermonindex_audio\bak_whisp_out\txt_chunked_out\/SID1189.mp3.txt_out.txt...
Traceback (most recent call last):
  File "C:\sermonindex_audio\chunk_paragraphs.py", line 136, in <module>
    main()
  File "C:\sermonindex_audio\chunk_paragraphs.py", line 125, in main
    chunk_paragraphs_dir(args.i, args.o)
  File "C:\sermonindex_audio\chunk_paragraphs.py", line 78, in chunk_paragraphs_dir
    _input_contents: str = input_file.read().encode("ascii", errors="ignore").decode().replace("\r\n", " ").replace("\n", " ")
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 101: character maps to <undefined>
PS C:\sermonindex_audio>

**Comment by turnkit** [comment]
Note: some errors are currently properly skipping -- e.g. below, but others crash the process still:
--
[INFO]: Writing to .\txt_chunked_out\/SID1262.mp3.txt_out.txt...
[INFO]: [17/1393] Sending file contents of .\txt_to_do/SID1263.mp3.txt to API server on 192.168.0.62:8000...
[INFO]: Writing to .\txt_chunked_out\/SID1263.mp3.txt_out.txt...
[ERROR]: Error, skipping file SID1263.mp3.txt
[INFO]: [18/1393] Sending file contents of .\txt_to_do/SID1264.mp3.txt to API server on 192.168.0.62:8000...
[INFO]: Writing to .\txt_chunked_out\/SID1264.mp3.txt_out.txt...
[INFO]: [19/1393] Sending file contents of .\txt_to_do/SID1265.mp3.txt to API server on 192.168.0.62:8000...
[INFO]: Writing to .\txt_chunked_out\/SID1265.mp3.txt_out.txt...
Traceback (most recent call last):
  File "C:\sermonindex_audio\chunk_paragraphs.py", line 136, in <module>
    main()
  File "C:\sermonindex_audio\chunk_paragraphs.py", line 125, in main
    chunk_paragraphs_dir(args.i, args.o)
  File "C:\sermonindex_audio\chunk_paragraphs.py", line 78, in chunk_paragraphs_dir
    _input_contents: str = input_file.read().encode("ascii", errors="ignore").decode().replace("\r\n", " ").replace("\n", " ")
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1098: character maps to <undefined>
PS C:\sermonindex_audio\bak_whisp_out>
