### ISSUE TITLE
Add additional INFO output during processing

### ISSUE THREAD

**Issue by turnkit** [V3ntus/quint#8]
Prefix the info line with current date and time.

Also please confirm that the filename is output on the info display when there is a success but also even if it fails.

Also please add an date and time stamp and a phrase such as "Paragraph chunking succeeded for file ..." or "Paragraph chunking FAILED for file..." for each file.

--
[INFO]: Writing to C:\sermonindex_audio\bak_whisp_out\txt_chunked_out/SID1189.mp3.txt_out.txt...

**Comment by turnkit** [comment]
Here's an example where the first file fails an currently there is no INFO output:
--
PS C:\sermonindex_audio\bak_whisp_out> .\do_quint_transcript.bat 192.168.0.62:8000

C:\sermonindex_audio\bak_whisp_out>set INPUT_FOLDER=.\txt_to_do

C:\sermonindex_audio\bak_whisp_out>set OUTPUT_FOLDER=.\txt_chunked_out\
Input folder is .\txt_to_do
Output folder is .\txt_chunked_out\
[INFO]: Input is a directory, assuming batch mode
[INFO]: Found 1448 files in .\txt_to_do
Traceback (most recent call last):
  File "C:\sermonindex_audio\chunk_paragraphs.py", line 136, in <module>
    main()
  File "C:\sermonindex_audio\chunk_paragraphs.py", line 125, in main
    chunk_paragraphs_dir(args.i, args.o)
  File "C:\sermonindex_audio\chunk_paragraphs.py", line 78, in chunk_paragraphs_dir
    _input_contents: str = input_file.read().encode("ascii", errors="ignore").decode().replace("\r\n", " ").replace("\n", " ")
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 101: character maps to <undefined>
PS C:\sermonindex_audio\bak_whisp_out>
